import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'

import { initFluidMotion, fluidPx, fluidValue, fluidEnd } from '../../skills/scroll-animation/assets/gsap/index'
import { scrubVideo } from '../../skills/scroll-animation/assets/gsap/scrub-video'
import { setupGsap } from '../../skills/scroll-animation/assets/gsap/setup'

// The v1 blocks still on this page (stage, count-up, fade-on-exit).
initFluidMotion(document)

// A tiny all-intra clip (generated by the repo root's `pretest` script into
// tests/.scratch, then copied to public/clip.mp4) -- every frame is a
// keyframe, so the scene can seek to an arbitrary frame every rAF without
// the stuck-then-jump symptom a long-GOP encode produces. Created before the
// travel section's ScrollTriggers: triggers are created in page order.
setupGsap()
scrubVideo(document.querySelector<HTMLElement>('[data-scene-root]')!, {
  fps: 30,
  headLoop: { fromFrame: 0, matchFrame: 5 },
  tailLoop: { fromFrame: 55 }
})

// Scaled travel (fluid-interop.md §3). The section is 200vh tall; both
// tweens run from its top reaching the viewport top over 900 drawn px of
// scroll, then hold. tests/distance-check.mjs scrolls past the end at two
// viewports and asserts each element moved 240 * --fluid.
gsap.registerPlugin(ScrollTrigger)
gsap.to('#travel-var', {
  '--scene-p': 1,
  ease: 'none',
  scrollTrigger: { trigger: '#travel', start: 'top top', end: fluidEnd(900), scrub: true, invalidateOnRefresh: true }
})
gsap.to('#travel-fn', {
  x: fluidValue(240),
  ease: 'none',
  scrollTrigger: { trigger: '#travel', start: 'top top', end: fluidEnd(900), scrub: true, invalidateOnRefresh: true }
})

// Canary: GSAP folds CSS translate into its own transform on the first
// transform tween (motion-architecture.md §7). distance-check.mjs asserts it.
gsap.to('#fold-canary', { y: 1, duration: 0.01 })

// fluidPx's `el` param (fluid-interop.md §3): #fluid-el-scope carries a
// literal --_fluid-m-ui, standing in for a registered mirror the fluid-design
// engine would write on a limited subtree (fluid-ui-grow-until-*). Reading
// through `el` must use that 500px/1000 = 0.5 rather than the page's own
// `ui` unit. distance-check.mjs asserts the exact value.
;(window as unknown as { __fluidPxScoped: number }).__fluidPxScoped = fluidPx(
  48,
  'ui',
  // A CHILD of the scope: the registered mirror doesn't inherit, so fluidPx
  // must walk up to #fluid-el-scope to find it.
  document.getElementById('fluid-el-child')!
)

// Exposed for tests/distance-check.mjs diagnostics.
;(window as unknown as { __ST: typeof ScrollTrigger }).__ST = ScrollTrigger
