import { initFluidMotion } from '../../scroll-animation/assets/gsap/src/index'

// A tiny all-intra clip (generated by the repo root's `pretest` script into
// tests/.scratch, then copied to public/clip.mp4) -- every frame is a
// keyframe, so ScrubStage can seek to an arbitrary frame every rAF without
// the stuck-then-jump symptom a long-GOP encode produces.
initFluidMotion(document, {
  scrubStage: () => ({
    fps: 30,
    headLoop: { fromFrame: 0, matchFrame: 5 },
    tailLoop: { fromFrame: 55 }
  })
})
