import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'

import { initFluidMotion, fluidValue, fluidEnd } from '../../scroll-animation/assets/gsap/src/index'

// A tiny all-intra clip (generated by the repo root's `pretest` script into
// tests/.scratch, then copied to public/clip.mp4) -- every frame is a
// keyframe, so ScrubStage can seek to an arbitrary frame every rAF without
// the stuck-then-jump symptom a long-GOP encode produces.
initFluidMotion(document, {
  scrubStage: () => ({
    fps: 30,
    headLoop: { fromFrame: 0, matchFrame: 5 },
    tailLoop: { fromFrame: 55 }
  })
})

// Scaled travel (fluid-interop.md §3). The section is 200vh tall; both
// tweens run from its top reaching the viewport top over 900 drawn px of
// scroll, then hold. tests/distance-check.mjs scrolls past the end at two
// viewports and asserts each element moved 240 * --fluid.
gsap.registerPlugin(ScrollTrigger)
gsap.to('#travel-var', {
  '--scene-p': 1,
  ease: 'none',
  scrollTrigger: { trigger: '#travel', start: 'top top', end: fluidEnd(900), scrub: true, invalidateOnRefresh: true }
})
gsap.to('#travel-fn', {
  x: fluidValue(240),
  ease: 'none',
  scrollTrigger: { trigger: '#travel', start: 'top top', end: fluidEnd(900), scrub: true, invalidateOnRefresh: true }
})

// Canary: GSAP folds CSS translate into its own transform on the first
// transform tween (motion-architecture.md §7). distance-check.mjs asserts it.
gsap.to('#fold-canary', { y: 1, duration: 0.01 })

// Exposed for tests/distance-check.mjs diagnostics.
;(window as unknown as { __ST: typeof ScrollTrigger }).__ST = ScrollTrigger
